marksApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    path("", views.userHome, name='Home'),
    path("<int:StanderdId>", views.standerdHandling, name='StanderdHandling'),
    path("<str:StanderdId>/<str:subjectId>",
         views.subjectHandling, name='subjectHandling'),
    path("<str:StanderdId>/<str:subjectId>/<str:marksrecordId>",
         views.addAndupdateMarks, name='addAndupdateMarks'),
]

marks_management/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("marksApp.urls")),
]

marksApp/models.py
from django.db import models


class Standerd(models.Model):

    CBSE = "CBSE"
    GSEB = "GSEB"
    Science = "Science"
    Commerce = "Commerce"

    MediumOfStudent = ((CBSE, "CBSE"),
                       (GSEB, "GSEB"),
                       (Science, "Science"),
                       (Commerce, "Commerce"))

    Id = models.AutoField(primary_key=True)
    Std = models.PositiveIntegerField()
    Medium = models.CharField(
        max_length=11, choices=MediumOfStudent, default=GSEB)
    Div = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        stdn = str(self.Std) + " "+self.Medium
        return stdn


class studentInfo(models.Model):
    id = models.AutoField(primary_key=True)
    HR_No = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    Middle_name = models.CharField(max_length=50)
    Last_name = models.CharField(max_length=50)
    Room_No = models.CharField(max_length=10)
    studentStd = models.ForeignKey(Standerd, on_delete=models.CASCADE)

    def __str__(self):
        return self.HR_No


class subject(models.Model):
    id = models.AutoField(primary_key=True)
    subject_Name = models.CharField(max_length=30)
    subjectStd = models.ForeignKey(Standerd, on_delete=models.CASCADE)

    def __str__(self):
        return self.subject_Name


class marksRecord(models.Model):
    Id = models.AutoField(primary_key=True)
    totalMarks = models.PositiveIntegerField()
    date = models.DateField()
    Subject = models.ForeignKey(subject, on_delete=models.CASCADE)

    def __str__(self):
        record = str(self.date) + " "+str(self.totalMarks)
        return record


class Marks(models.Model):
    Id = models.AutoField(primary_key=True)
    achivedMarks = models.PositiveIntegerField()
    Student = models.ForeignKey(studentInfo, on_delete=models.CASCADE)
    totalMarks = models.ForeignKey(marksRecord, on_delete=models.CASCADE)

    def __str__(self):
        record = str(self.totalMarks.date) + " "+str(self.achivedMarks)
        return record

marksApp/forms.py
from django import forms
from marksApp.models import studentInfo, Standerd, subject, Marks, marksRecord


class standerdForm(forms.ModelForm):
    class Meta:
        model = Standerd
        fields = ('Std', 'Medium', 'Div',)


class subjectForm(forms.ModelForm):
    class Meta:
        model = subject
        fields = ('subject_Name',)


class studentForm(forms.ModelForm):
    class Meta:
        model = studentInfo
        fields = ('HR_No', 'first_name', 'Middle_name',
                  'Last_name', 'Room_No',)


class marksForm(forms.ModelForm):
    class Meta:
        model = Marks
        fields = ('achivedMarks',)

marksApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,  login, logout
from django.contrib.auth.forms import UserChangeForm
from marksApp.models import studentInfo, Standerd, subject, Marks, marksRecord
from marksApp.forms import standerdForm, subjectForm, studentForm, marksForm
from django.forms import formset_factory
from django.http import HttpResponse
from django.contrib import messages

# Create your views here.

# userhome handling


def userHome(request):
    try:
        stdForm = standerdForm()
        if request.POST.get("deleteStanderd"):
            msgStd = Standerd.objects.get(
                Id=request.POST.get("deleteStanderd"))
            messages.info(request, "Standerd" + str(msgStd.Std) + " " +
                          str(msgStd.Div) + " " + str(msgStd.Medium) + " deleted successfully.")
            Standerd.objects.filter(
                Id=request.POST.get("deleteStanderd")).delete()
            return redirect("/")

        if request.POST.get("AddNewStanderd"):
            form = standerdForm(request.POST)
            if form.is_valid():
                form.save()
            messages.info(request, "New standerd is added successfully.")
            return redirect("/")

        if request.POST.get("updateStanderd"):

            currentStanderd = Standerd.objects.get(
                Id=request.POST.get("updateStanderd"))
            std = currentStanderd.Std
            medium = currentStanderd.Medium
            div = currentStanderd.Div

            formToUpdate = standerdForm(
                request.POST or None, instance=currentStanderd)
            if formToUpdate.is_valid():
                formToUpdate.save()

            messages.info(request, str(std) + " " + str(div) + " "+str(medium) +
                          " is updated to " + str(currentStanderd .Std)+" "+str(currentStanderd .Div)+" "+str(currentStanderd .Medium))
            return redirect("/")

        allStanderd = Standerd.objects.all()
        context = {'allStanderd': allStanderd, 'standerdForm': stdForm}
        return render(request, 'MarksApp/home.html', context)

    except:
        return render(request, 'MarksApp/error.html')


# standerd page handling function


def standerdHandling(request, StanderdId):

    try:
        subForm = subjectForm()
        stdForm = studentForm()

    # subject handling

        if request.POST.get("deleteSubject"):
            msgsub = subject.objects.get(id=request.POST.get("deleteSubject"))
            messages.info(request, str(msgsub.subject_Name) +
                          " is deleted successfully")
            subject.objects.filter(
                id=request.POST.get("deleteSubject")).delete()
            return redirect("/"+str(StanderdId))

        if request.POST.get("AddNewSubject"):
            form = subjectForm(request.POST)
            if form.is_valid():
                fromSave = form.save(commit=False)
                fromSave.subjectStd = Standerd.objects.get(Id=StanderdId)
                fromSave.save()
            messages.info(request, "New subject added successfully")
            return redirect('/'+str(StanderdId))

        if request.POST.get("updateSubject"):

            currentSubject = subject.objects.get(
                id=request.POST.get("updateSubject"))
            currsub = currentSubject.subject_Name

            formToUpdate = subjectForm(
                request.POST or None, instance=currentSubject)
            if formToUpdate.is_valid():
                formToUpdate.save()

            messages.info(request, str(currsub) +
                          " is updated to "+str(currentSubject.subject_Name))
            return redirect('/'+str(StanderdId))

    # student handling

        if request.POST.get("deleteStudent"):
            msgstudent = studentInfo.objects.get(
                id=request.POST.get("deleteStudent"))
            messages.info(request, str(msgstudent.first_name)+" "+str(msgstudent.Middle_name) +
                          " "+str(msgstudent.Last_name)+" is deleted successfully")
            studentInfo.objects.filter(
                id=request.POST.get("deleteStudent")).delete()
            return redirect('/'+str(StanderdId))

        if request.POST.get("AddNewStudent"):
            form = studentForm(request.POST)
            if form.is_valid():
                fromSave = form.save(commit=False)
                fromSave.studentStd = Standerd.objects.get(Id=StanderdId)
                fromSave.save()
            messages.info(request, "New student is added successfully")
            return redirect('/'+str(StanderdId))

        if request.POST.get("updateStudent"):

            currentSubject = studentInfo.objects.get(
                id=request.POST.get("updateStudent"))

            formToUpdate = studentForm(
                request.POST or None, instance=currentSubject)
            if formToUpdate.is_valid():
                formToUpdate.save()
            messages.info(request, "Student is updated successfully.")
            return redirect('/'+str(StanderdId))

        allSubject = subject.objects.filter(subjectStd=StanderdId)
        allStudent = studentInfo.objects.filter(studentStd=StanderdId)
        currentStanderd = Standerd.objects.get(Id=StanderdId)

        context = {'currentStanderd': currentStanderd, 'allSubject': allSubject, 'subjectForm': subForm,
                   'StanderdId': StanderdId, 'studentForm': stdForm, 'allStudent': allStudent, }

        return render(request, 'MarksApp/standerdDetails.html', context)

    except:
        return render(request, 'MarksApp/error.html')


def subjectHandling(request, StanderdId, subjectId):
    try:
        allStudent = studentInfo.objects.filter(studentStd=StanderdId)
        currentSubject = subject.objects.get(id=subjectId)
        currentStanderd = Standerd.objects.get(Id=StanderdId)

        if request.POST.get("AddNewMarksRecord"):
            TotalMarks = request.POST['TotalMarks']
            CurrentDate = request.POST['CurrentDate']

            marksObject = marksRecord.objects.create(
                totalMarks=TotalMarks, date=CurrentDate, Subject=currentSubject)
            marksObject.save()
            messages.info(request, "New record added successfully")
            return redirect("/"+str(StanderdId)+"/"+str(subjectId))

        if request.POST.get("deleteMarksRecord"):

            messages.info(request, "Marks record deleted successfully.")
            marksRecord.objects.filter(
                Id=request.POST.get("deleteMarksRecord")).delete()
            return redirect("/"+str(StanderdId)+"/"+str(subjectId))

        if request.POST.get("updateMarksRecord"):
            TotalMarks = request.POST['TotalMarks']
            CurrentDate = request.POST['CurrentDate']

            marksRecord.objects.filter(Id=request.POST.get(
                "updateMarksRecord")).update(totalMarks=TotalMarks, date=CurrentDate)
            messages.info(request, "marks record updated successfully.")
            return redirect("/"+str(StanderdId)+"/"+str(subjectId))

        AllMarksRecords = marksRecord.objects.filter(Subject=subjectId)

        context = {'Subject': currentSubject,
                   'Standerd': currentStanderd, 'marksRecords': AllMarksRecords, }

        return render(request, 'MarksApp/subjectDetails.html', context)
    except:
        return render(request, 'MarksApp/error.html')
# update and add the marks of the student in particuler subject record


def addAndupdateMarks(request, StanderdId, subjectId, marksrecordId):

    try:

        allStudent = studentInfo.objects.filter(studentStd=StanderdId)
        currentSubject = subject.objects.get(id=subjectId)
        currentStanderd = Standerd.objects.get(Id=StanderdId)
        currentRecord = marksRecord.objects.get(Id=marksrecordId)

        if request.POST.get("AddMarksStudent"):

            MarksRecordToAdd = marksRecord.objects.get(
                Id=request.POST['AddMarksStudent'])
            marksWithCurrentRecord = Marks.objects.filter(
                totalMarks=MarksRecordToAdd)

        # code to update added marks
            if marksWithCurrentRecord.exists():
                for student in allStudent:
                    x = 'AchivedMarks' + student.HR_No
                    achivedMarks = request.POST[x]
                    marksToUpdate = Marks.objects.get(
                        Student=student, totalMarks=MarksRecordToAdd)
                    marksToUpdate.achivedMarks = achivedMarks
                    marksToUpdate.save()

        # code to add new marks
            else:

                for student in allStudent:
                    x = 'AchivedMarks' + student.HR_No
                    achivedMarks = request.POST[x]
                    MarksObject = Marks.objects.create(
                        achivedMarks=achivedMarks, Student=student, totalMarks=MarksRecordToAdd)
                    MarksObject.save()
            messages.info(request, "Marks of Students updated successfully.")
            return redirect("/"+str(StanderdId)+"/" + str(subjectId)+"/" + str(marksrecordId))

        marks_list = []

        for student in allStudent:
            try:
                marksOfStudent = Marks.objects.get(
                    Student=student, totalMarks=marksrecordId)
                marks_list.append(marksOfStudent)
            except:
                marks_list.append(None)

        context = {'allStudentAndMarks': zip(allStudent, marks_list), 'allStudent': allStudent, 'Subject': currentSubject,
                   'Standerd': currentStanderd, 'Record': currentRecord}


marksApp/templates/MarksApp/error.html
{% extends "MarksApp/base.html" %}
<!--title-->
{% block title %}Error page{% endblock %}
<!--body-->
{% block body %}

<div class="page">
  <h1 class="text-center">Error</h1>

  <h2 class="text-center">Some error occured. Please, Go back to home and try again.</h2>

  <div class="text-center">
    <a href="{% url 'Home' %}">
      <div class="button">
        <div class="green">Home</div>
      </div>
    </a>
  </div>
</div>

<style>
  .page {
    margin-top: 150px;
    margin-bottom: 150px;
  }
  .button {
    background: linear-gradient(to bottom, #14eb49 5%, green 100%);
    background-color: #14eb49;
    border-radius: 11px;
    border: 3px solid green;
    display: inline-block;
    cursor: pointer;
    color: #ffffff;
    font-family: Trebuchet MS;
    font-size: 28px;
    font-weight: bold;
    padding: 7px 76px;
    text-decoration: none;
    text-shadow: 2px 2px 0px grey;
    margin: 50px;
  }

  .button:hover {
    background: linear-gradient(to bottom, green 5%, #14eb49 100%);
    background-color: green;
  }

  .button:active {
    position: relative;
    top: 1px;
  }
</style>
{% endblock %}

marksApp/templates/MarksApp/home.html
{% extends "MarksApp/base.html" %}

{% block title%}Home{% endblock  %}

{% block body %}

<style>
.colCrop {
    width: 208px;
    -ms-flex-preferred-size: 0;
    /* flex-basis: 0; */
    /* -webkit-box-flex: 1; */
    -ms-flex-positive: 1;
    /* flex-grow: 1; */
    /* max-width: 19%; */
    background: whitesmoke;
    padding: 10px;
    margin: 5px;
}
.rowCrop {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin:10px 15px;

}
.containerCrop {
    max-width: 100%;
}

</style>

<!--add new standerd modal-->

<div class="container mt-3">
  <div class="row">
    <div class="col-10.5 mr-auto">
      <h3 class="h3Crop" >Standerd list</h3>
    </div>
    <div class="col-1.5">
<button type="button" class="btn mr-2 " style="background-color:lightblue" data-toggle="modal" data-target="#standerdModal">
Add new Standerd
</button>
    </div>
  </div>
</div>

<div class="modal fade" id="standerdModal" tabindex="-1" aria-labelledby="standerdModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="standerdModalTitle">Add new standerd</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

<!--Add new standerd Form-->

        <form action= "/" method='post' enctype="multipart/form-data">
           {% csrf_token %}
          <p><label for="id_Std">Std:</label> <input type="number" name="Std" min="1" max="12" required id="id_Std"></p>
          <p><label for="id_Medium">Medium:</label> 
              <select name="Medium" id="id_Medium">
              <option value="CBSE">CBSE</option>

              <option value="GSEB" selected>GSEB</option>

              <option value="Science">Science</option>

              <option value="Commerce">Commerce</option>

              </select>
            </p>
            <p><label for="id_Div">Div:</label> <input type="text" name="Div" maxlength="1" style='text-transform:uppercase' id="id_Div"></p>
        <button type="submit" name="AddNewStanderd" value="1" class="btn btn-primary">Submit</button>
        </form>

      </div>
    </div>
  </div>
</div>

      

<!--standerd showing on the homepage-->

<div class="containerCrop">
  <div class="rowCrop">
      {% for Standerd in allStanderd %}
     <a href="/{{Standerd.Id}}"> <div class="colCrop">
          <center><h3>{{Standerd.Std}} - {{Standerd.Div}}</h3>
      
    <h5>{{Standerd.Medium}}</h5></center></a>
    <form action="/" method="POST">
    {% csrf_token %}
    <button type=submit name='deleteStanderd' value='{{Standerd.Id}}'>Delete</button>
    </form>
   <button type="button" class="btn mr-2 " style="background-color:lightblue" data-toggle="modal" data-target="#updatestanderdModal{{Standerd.Id}}">
  update
  </button>

  <!--update standerd modal-->

<div class="modal fade" id="updatestanderdModal{{Standerd.Id}}" tabindex="-1" aria-labelledby="updatestanderdModal{{Standerd.Id}}" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updatestanderdModalTitle{{Standerd.Id}}">update the standerd</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <form action= "/" method='post' enctype="multipart/form-data">
           {% csrf_token %}
           
           {% comment %} {{standerdForm.as_p}} {% endcomment %}
           
            <p><label for="id_Std">Std:</label> <input type="number" value="{{Standerd.Std}}" name="Std" min="1" max="12" required id="id_Std"></p>
          <p><label for="id_Medium">Medium:</label> 

              <select name="Medium" id="id_Medium">
              <option value="CBSE">CBSE</option>
              <option value="GSEB" selected>GSEB</option>
              <option value="Science">Science</option>
              <option value="Commerce">Commerce</option>
              </select>
            </p>
            <p><label for="id_Div">Div:</label> <input type="text" value="{{Standerd.Div}}" name="Div" maxlength="1" id="id_Div" style='text-transform:uppercase'></p>

        <button type=submit name="updateStanderd" value="{{Standerd.Id}}" class="btn btn-primary">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>

      
      </div>
      {% if forloop.counter|divisibleby:4%}
  </div>
    <div class="rowCrop">
      {% endif %} 
      {% endfor %}
  </div>
</div>



{% endblock  %}

marksApp/templates/MarksApp/standerdDetails.html
{% extends "MarksApp/base.html" %}

{% block title%}standerd page{% endblock  %}

{% block body %}

<style>
.colCrop {
    width: 208px;
    -ms-flex-preferred-size: 0;
    /* flex-basis: 0; */
    /* -webkit-box-flex: 1; */
    -ms-flex-positive: 1;
    /* flex-grow: 1; */
    /* max-width: 19%; */
    background: whitesmoke;
    padding: 10px;
    margin: 5px;
}
.rowCrop {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    margin:10px 15px;

}
.containerCrop {
    max-width: 100%;
}

</style>

<h2>{{currentStanderd.Std}} {{currentStanderd.Div}} {{currentStanderd.Medium}}</h2>

<!--add new subject modal-->

<div class="container mt-3">
  <div class="row">
    <div class="col-10.5 mr-auto">
      <h3 class="h3Crop" >Subject list</h3>
    </div>
    <div class="col-1.5">
<button type="button" class="btn mr-2 " style="background-color:lightblue" data-toggle="modal" data-target="#subjectModal">
Add new Subject
</button>
    </div>
  </div>
</div>

<div class="modal fade" id="subjectModal" tabindex="-1" aria-labelledby="subjectModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="subjectModalTitle">Add new subject</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

<!--Add new subject Form-->

        <form action= "/{{StanderdId}}" method='post' enctype="multipart/form-data">
           {% csrf_token %}
           {{subjectForm.as_p}}
        <button type="submit" name="AddNewSubject" value="1" class="btn btn-primary">Submit</button>
        </form>

      </div>
    </div>
  </div>
</div>


<div class="containerCrop">
  <div class="rowCrop">
      {% for Subject in allSubject %}
      
     <a href="{% url 'subjectHandling' StanderdId=StanderdId subjectId=Subject.id %}"> <div class="colCrop">
          <center><h3>{{Subject.subject_Name}}</h3>
      </center>
    </a>
<form action="/{{StanderdId}}" method="POST">
    {% csrf_token %}
    <button type=submit name='deleteSubject' value='{{Subject.id}}'>Delete</button>
    </form>
    <button type="button" class="btn mr-2 " style="background-color:lightblue" data-toggle="modal" data-target="#updatesubjectModal{{Subject.id}}">
  update
  </button>

  <!--update subject modal-->

<div class="modal fade" id="updatesubjectModal{{Subject.id}}" tabindex="-1" aria-labelledby="updatesubjectModal{{Subject.id}}" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updatesubjectModal{{Subject.id}}">update the subject</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <form action= "/{{StanderdId}}" method='post' enctype="multipart/form-data">
           {% csrf_token %}
           {% comment %} {{subjectForm.as_p}}          {% endcomment %}
           <p><label for="id_subject_Name">Subject Name:</label> <input type="text" name="subject_Name" value="{{Subject.subject_Name}}" maxlength="30" required id="id_subject_Name"></p>
        <button type=submit name="updateSubject" value="{{Subject.id}}" class="btn btn-primary">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>


      </div>
      {% if forloop.counter|divisibleby:4%}
  </div>
    <div class="rowCrop">
      {% endif %}
      {% endfor %}
  </div>
</div>


<!-------------------------------------------------------------------------------------------------------->


<!--student showing on each standerd page-->


<div class="container mt-3">
  <div class="row">
    <div class="col-10.5 mr-auto">
      <h3 class="h3Crop" >student list</h3>
    </div>
    <div class="col-1.5">
<button type="button" class="btn mr-2 " style="background-color:lightblue" data-toggle="modal" data-target="#studentModal">
Add new student
</button>
    </div>
  </div>
</div>

<div class="modal fade" id="studentModal" tabindex="-1" aria-labelledby="studentModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="studentModalTitle">Add new student</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

<!--Add new student Form-->

        <form action= "/{{StanderdId}}" method='post' enctype="multipart/form-data">
           {% csrf_token %}
           {{studentForm.as_p}}
        <button type="submit" name="AddNewStudent" value="1" class="btn btn-primary">Submit</button>
        </form>

      </div>
    </div>
  </div>
</div>


<!--student showing on each standerd page-->

<div class="containerCrop">
  <div class="rowCrop">
     {% for Student in allStudent %}
     <div class="colCrop">
      <center><p>{{Student.first_name}}  {{Student.Middle_name}}  {{Student.Last_name}}</p>
          <p>{{Student.Room_No}}</p>
      </center>
    <form action="/{{StanderdId}}" method="POST">
    {% csrf_token %}
    <button type=submit name='deleteStudent' value='{{Student.id}}'>Delete</button>
    </form>

    <button type="button" class="btn mr-2 " style="background-color:lightblue" data-toggle="modal" data-target="#updatestudentModal{{Student.id}}">
  update
  </button>

  <!--update student modal-->

<div class="modal fade" id="updatestudentModal{{Student.id}}" tidabindex="-1" aria-labelledby="updatestudentModal{{Student.id}}" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="updatestudentModal{{Student.id}}">update student information</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <form action= "/{{StanderdId}}" method='post' enctype="multipart/form-data">
           {% csrf_token %}
           {% comment %} {{studentForm.as_p}}       {% endcomment %}
            <p><label for="id_HR_No">HR No:</label> <input type="text" value="{{Student.HR_No}}" name="HR_No" maxlength="20" required id="id_HR_No"></p>
            <p><label for="id_first_name">First name:</label> <input type="text" value="{{Student.first_name}}" name="first_name" maxlength="50" required id="id_first_name"></p>
            <p><label for="id_Middle_name">Middle name:</label> <input type="text" value="{{Student.Middle_name}}" name="Middle_name" maxlength="50" required id="id_Middle_name"></p>
            <p><label for="id_Last_name">Last name:</label> <input type="text" value="{{Student.Last_name}}" name="Last_name" maxlength="50" required id="id_Last_name"></p>
            <p><label for="id_Room_No">Room No:</label> <input type="text" value="{{Student.Room_No}}" name="Room_No" maxlength="10" required id="id_Room_No"></p>
        <button type=submit name="updateStudent" value="{{Student.id}}" class="btn btn-primary">Update</button>
        </form>
      </div>
    </div>
  </div>
</div>
      </div>
      {% if forloop.counter|divisibleby:1%}
  </div>
    <div class="rowCrop">
      {% endif %}
      {% endfor %}
  </div>
</div>




{% endblock  %}